"""user.test_reminders

Revision ID: 35b2982484ec
Revises: 937ac216ffac
Create Date: 2023-02-06 23:12:25.862472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b2982484ec'
down_revision = '937ac216ffac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_reminders', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test_reminders')

    # ### end Alembic commands ###
