"""expand user.grad_year

Revision ID: e81459e1ee20
Revises: 35b2982484ec
Create Date: 2023-05-12 13:14:14.978813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81459e1ee20'
down_revision = '35b2982484ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('grad_year',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('grad_year',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
