"""user.timezone to str

Revision ID: d5110ea8d5d5
Revises: e81459e1ee20
Create Date: 2024-06-25 02:16:56.622095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5110ea8d5d5'
down_revision = 'e81459e1ee20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'timezone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'timezone',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
