"""score report generator

Revision ID: 1e816d936486
Revises: d5110ea8d5d5
Create Date: 2024-09-22 01:18:03.154856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e816d936486'
down_revision = 'd5110ea8d5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=True),
    sa.Column('test_code', sa.String(length=8), nullable=True),
    sa.Column('rw_score', sa.Integer(), nullable=True),
    sa.Column('m_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=True),
    sa.Column('json_path', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('test_score')
    # ### end Alembic commands ###
