"""org-partner one-to-one

Revision ID: 4b364c66798d
Revises: 825e2262cc76
Create Date: 2025-09-18 09:01:13.467006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b364c66798d'
down_revision = '825e2262cc76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_organization_partner_id', ['partner_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint('uq_organization_partner_id', type_='unique')

    # ### end Alembic commands ###
