"""org.act_spreadsheet_id

Revision ID: 207947f88f1c
Revises: ea1fa46c0973
Create Date: 2025-06-29 14:08:04.969371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207947f88f1c'
down_revision = 'ea1fa46c0973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('act_spreadsheet_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sat_spreadsheet_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('spreadsheet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spreadsheet_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('sat_spreadsheet_id')
        batch_op.drop_column('act_spreadsheet_id')

    # ### end Alembic commands ###
