"""org.spreadsheet_url to org.spreadsheet.id

Revision ID: ea1fa46c0973
Revises: 068de433a246
Create Date: 2025-05-06 00:12:40.500984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1fa46c0973'
down_revision = '068de433a246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spreadsheet_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('spreadsheet_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spreadsheet_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('spreadsheet_id')

    # ### end Alembic commands ###
