"""org table

Revision ID: 068de433a246
Revises: d2537aaf23c4
Create Date: 2025-05-05 23:18:06.445651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '068de433a246'
down_revision = 'd2537aaf23c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('spreadsheet_url', sa.String(length=255), nullable=True),
    sa.Column('color1', sa.String(length=7), nullable=True),
    sa.Column('color2', sa.String(length=7), nullable=True),
    sa.Column('color3', sa.String(length=7), nullable=True),
    sa.Column('logo_path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.drop_table('user_copy')
    op.drop_table('test_date_copy')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_organization', 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_organization', type_='foreignkey')

    op.create_table('test_date_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('test', mysql.VARCHAR(collation='utf8_bin', length=24), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8_bin', length=24), nullable=True),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.Column('late_date', sa.DATE(), nullable=True),
    sa.Column('other_date', sa.DATE(), nullable=True),
    sa.Column('score_date', sa.DATE(), nullable=True),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_copy',
    sa.Column('id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('last_viewed', mysql.DATETIME(), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('timezone', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8_bin', length=24), nullable=True),
    sa.Column('role', mysql.VARCHAR(collation='utf8_bin', length=24), nullable=True),
    sa.Column('tutor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('organization')
    # ### end Alembic commands ###
