"""organization.partner_id

Revision ID: 7ea558fa8622
Revises: 207947f88f1c
Create Date: 2025-09-10 21:21:33.319158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea558fa8622'
down_revision = '207947f88f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_organization_partner_id', 'user', ['partner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint('fk_organization_partner_id', type_='foreignkey')
        batch_op.drop_column('partner_id')

    # ### end Alembic commands ###
