"""user.subject

Revision ID: 098ecf9088df
Revises: 94806016cb62
Create Date: 2025-11-29 12:06:29.119443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098ecf9088df'
down_revision = '94806016cb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
