"""remove user.organization_id

Revision ID: 94806016cb62
Revises: 4b364c66798d
Create Date: 2025-09-18 11:42:46.295540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94806016cb62'
down_revision = '4b364c66798d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_organization', type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_organization', 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###
