"""org.font_color

Revision ID: 825e2262cc76
Revises: 7ea558fa8622
Create Date: 2025-09-11 13:53:33.797920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825e2262cc76'
down_revision = '7ea558fa8622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('font_color')

    # ### end Alembic commands ###
