"""org.ss_logo_path

Revision ID: 4baee5912924
Revises: bbfb01918122
Create Date: 2025-12-26 14:12:42.297203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4baee5912924'
down_revision = 'bbfb01918122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ss_logo_path', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('ss_logo_path')

    # ### end Alembic commands ###
