"""Add color fields to Organization model

Revision ID: f6427fd2c391
Revises: 9544c2edd8e0
Create Date: 2025-05-03 12:40:51.054833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6427fd2c391'
down_revision = '9544c2edd8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color1', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('color2', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('color3', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('color3')
        batch_op.drop_column('color2')
        batch_op.drop_column('color1')

    # ### end Alembic commands ###
