"""Add Organization model and organization_id to User

Revision ID: 9544c2edd8e0
Revises: d2537aaf23c4
Create Date: 2025-05-03 12:05:53.352873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9544c2edd8e0'
down_revision = 'd2537aaf23c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_organization', 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_organization', type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
