"""user.pronouns

Revision ID: 1a3ca17598d7
Revises: a4a5f2559538
Create Date: 2026-01-19 00:30:14.470073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3ca17598d7'
down_revision = 'a4a5f2559538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronouns', sa.String(length=16), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('pronouns')

    # ### end Alembic commands ###
