"""user.access_level change to int

Revision ID: 60f6b7b9911c
Revises: d35c4ef5f6c7
Create Date: 2026-02-09 23:36:27.169424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f6b7b9911c'
down_revision = 'd35c4ef5f6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('access_level',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('access_level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True)

    # ### end Alembic commands ###
