"""user sat_ss_id, act_ss_id, access_level

Revision ID: d35c4ef5f6c7
Revises: 1ab5ad018889
Create Date: 2026-02-02 00:03:14.505692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35c4ef5f6c7'
down_revision = '1ab5ad018889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sat_ss_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('act_ss_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('access_level', sa.String(length=24), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('access_level')
        batch_op.drop_column('act_ss_id')
        batch_op.drop_column('sat_ss_id')

    # ### end Alembic commands ###
