"""user.referrer, org.role, org.timezone

Revision ID: 1ab5ad018889
Revises: 1a3ca17598d7
Create Date: 2026-01-31 15:47:17.269791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab5ad018889'
down_revision = '1a3ca17598d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('referrer')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
